// lib/demo/fixtures-bretagne.ts — Voyage fictif FAMILLE pour le Mode Démo.
//
// Famille : Lina (organisatrice) + Tom + Sam (frère 14 ans) + Inès (sœur 11 ans)
// Côte de Granit Rose · 7 jours · 2026-08-08 → 2026-08-14
// Statut : à venir — completions vides, checklist partiellement cochée

import type {
  LocalTrip,
  LocalTripMember,
  LocalDay,
  LocalActivity,
  LocalActivityCompletion,
  LocalSpot,
  LocalExpense,
  LocalExpenseSplit,
  LocalChecklistItem,
  LocalChecklistCompletion,
  LocalGuideCard,
} from '@/lib/db/schema'

import {
  DEMO_USER_ID,
  DEMO_PARTNER_ID,
  DEMO_SAM_ID,
  DEMO_INES_ID,
} from './ids'

const NOW = new Date('2026-05-21T10:00:00Z').toISOString()
const BRETAGNE = 'demo-trip-bretagne'

// ─── Trip ────────────────────────────────────────────────────────────────────
export const bretagneTrip: LocalTrip = {
  id: BRETAGNE,
  owner_id: DEMO_USER_ID,
  name: 'Côte de Granit Rose',
  destination: 'Perros-Guirec → Saint-Malo',
  start_date: '2026-08-08',
  end_date: '2026-08-14',
  trip_type: 'beach',
  currency: 'EUR',
  total_budget: 1450,
  cover_color: '#3D362C',
  join_code: 'MKT-DEMO6',
  hero_image_url: '/heroes/beach/2.jpg',
  hero_image_uploaded: false,
  created_at: NOW,
  updated_at: NOW,
}

// ─── Members ──────────────────────────────────────────────────────────────────
export const bretagneMembers: LocalTripMember[] = [
  { trip_id: BRETAGNE, user_id: DEMO_USER_ID,    role: 'owner',  joined_at: NOW },
  { trip_id: BRETAGNE, user_id: DEMO_PARTNER_ID, role: 'editor', joined_at: NOW },
  { trip_id: BRETAGNE, user_id: DEMO_SAM_ID,     role: 'viewer', joined_at: NOW },
  { trip_id: BRETAGNE, user_id: DEMO_INES_ID,    role: 'viewer', joined_at: NOW },
]

// ─── Days ─────────────────────────────────────────────────────────────────────
export const bretagneDays: LocalDay[] = [
  {
    id: `${BRETAGNE}-d1`,
    trip_id: BRETAGNE,
    day_number: 1,
    date: '2026-08-08',
    label: 'Jour 1',
    theme: 'Arrivée · Perros-Guirec',
    zone: 'Perros-Guirec',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d2`,
    trip_id: BRETAGNE,
    day_number: 2,
    date: '2026-08-09',
    label: 'Jour 2',
    theme: 'Ploumanac\'h · Chaos granitique',
    zone: 'Ploumanac\'h',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d3`,
    trip_id: BRETAGNE,
    day_number: 3,
    date: '2026-08-10',
    label: 'Jour 3',
    theme: 'Île de Bréhat',
    zone: 'Bréhat',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d4`,
    trip_id: BRETAGNE,
    day_number: 4,
    date: '2026-08-11',
    label: 'Jour 4',
    theme: 'Roscoff · Château de Tonquédec',
    zone: 'Roscoff / Lannion',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d5`,
    trip_id: BRETAGNE,
    day_number: 5,
    date: '2026-08-12',
    label: 'Jour 5',
    theme: 'Cap Fréhel · Fort La Latte',
    zone: 'Cap Fréhel',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d6`,
    trip_id: BRETAGNE,
    day_number: 6,
    date: '2026-08-13',
    label: 'Jour 6',
    theme: 'Saint-Malo intra-muros',
    zone: 'Saint-Malo',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d7`,
    trip_id: BRETAGNE,
    day_number: 7,
    date: '2026-08-14',
    label: 'Jour 7',
    theme: 'Dinan médiéval · Retour',
    zone: 'Dinan',
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Activities ───────────────────────────────────────────────────────────────
export const bretagneActivities: LocalActivity[] = [
  // ── J1 : Arrivée Perros-Guirec + plage Trestraou ──────────────────────────
  {
    id: `${BRETAGNE}-d1-a0`,
    day_id: `${BRETAGNE}-d1`,
    time: '11:00',
    title: 'Arrivée au gîte Les Hortensias',
    subtitle: 'Check-in Perros-Guirec · 7 nuits',
    category: 'accommodation',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d1-a1`,
    day_id: `${BRETAGNE}-d1`,
    time: '13:00',
    title: 'Crêperie du Port',
    subtitle: 'Galettes complètes pour tout le monde — Sam prend celle au poulet',
    category: 'food',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d1-a2`,
    day_id: `${BRETAGNE}-d1`,
    time: '15:00',
    title: 'Plage de Trestraou',
    subtitle: 'Sable fin, eau fraîche — Inès repère déjà les coquillages',
    category: 'nature',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d1-a3`,
    day_id: `${BRETAGNE}-d1`,
    time: '18:30',
    title: 'Mini-golf de Trestraou',
    subtitle: '18 trous face à la mer — Sam gagne, Inès proteste',
    category: 'activity',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d1-a4`,
    day_id: `${BRETAGNE}-d1`,
    time: '20:00',
    title: 'Barbecue au gîte',
    subtitle: 'Saucisses + légumes grillés, rosé pour les adultes',
    category: 'food',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── J2 : Sentier des douaniers Ploumanac'h + chaos granit rose ────────────
  {
    id: `${BRETAGNE}-d2-a0`,
    day_id: `${BRETAGNE}-d2`,
    time: '09:00',
    title: 'Sentier des Douaniers — tronçon Ploumanac\'h',
    subtitle: '7 km A/R · chaos de granit rose · adapté enfants avec bonnes chaussures',
    category: 'sport',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d2-a1`,
    day_id: `${BRETAGNE}-d2`,
    time: '11:30',
    title: 'Phare de Mean Ruz',
    subtitle: 'Le phare rouge au milieu des rochers — photo de famille obligatoire',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d2-a2`,
    day_id: `${BRETAGNE}-d2`,
    time: '13:00',
    title: 'Pique-nique Plage de Saint-Guirec',
    subtitle: 'Sandwichs + jus · Inès repart avec 12 coquillages dans les poches',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d2-a3`,
    day_id: `${BRETAGNE}-d2`,
    time: '15:00',
    title: 'Balade à vélo sur la voie verte',
    subtitle: 'Location 4 vélos — Sam veut aller vite, Inès ramasse des cailloux',
    category: 'sport',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d2-a4`,
    day_id: `${BRETAGNE}-d2`,
    time: '19:30',
    title: 'Dîner — La Clarté, crêperie',
    subtitle: 'Galette chèvre-miel + kouign-amann maison',
    category: 'food',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── J3 : Île de Bréhat ────────────────────────────────────────────────────
  {
    id: `${BRETAGNE}-d3-a0`,
    day_id: `${BRETAGNE}-d3`,
    time: '08:30',
    title: 'Vedette depuis Pointe de l\'Arcouest',
    subtitle: '10 min de traversée · billet A/R famille',
    category: 'activity',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d3-a1`,
    day_id: `${BRETAGNE}-d3`,
    time: '09:30',
    title: 'Tour de l\'île à pied — Nord sauvage',
    subtitle: 'Pas de voitures sur l\'île · Sam voulait surfer mais le courant dit non',
    category: 'sport',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d3-a2`,
    day_id: `${BRETAGNE}-d3`,
    time: '12:30',
    title: 'Déjeuner La Vieille Auberge',
    subtitle: 'Poisson du jour · vue sur l\'anse de la Corderie',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d3-a3`,
    day_id: `${BRETAGNE}-d3`,
    time: '15:00',
    title: 'Moulin à Vent de Bréhat',
    subtitle: 'Vieux moulin + vue panoramique sur l\'archipel',
    category: 'culture',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d3-a4`,
    day_id: `${BRETAGNE}-d3`,
    time: '17:00',
    title: 'Retour vedette',
    subtitle: 'Inès a rempli un sachet de coquillages roses — Tom soupire',
    category: 'activity',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── J4 : Roscoff + château de Tonquédec ──────────────────────────────────
  {
    id: `${BRETAGNE}-d4-a0`,
    day_id: `${BRETAGNE}-d4`,
    time: '09:30',
    title: 'Marché de Roscoff',
    subtitle: 'Légumes locaux, poissons fumés, crêpes dentel pour le petit-déj',
    category: 'food',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d4-a1`,
    day_id: `${BRETAGNE}-d4`,
    time: '11:00',
    title: 'Jardin Exotique de Roscoff',
    subtitle: 'Cactus géants au bord de la mer — Inès est épatée',
    category: 'nature',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d4-a2`,
    day_id: `${BRETAGNE}-d4`,
    time: '13:30',
    title: 'Repas L\'Écume des Jours',
    subtitle: 'Moules marinières · frites maison · cidre breton',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d4-a3`,
    day_id: `${BRETAGNE}-d4`,
    time: '15:30',
    title: 'Château de Tonquédec',
    subtitle: 'Ruines médiévales à explorer librement — Sam joue aux chevaliers',
    category: 'culture',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── J5 : Cap Fréhel + Fort La Latte ──────────────────────────────────────
  {
    id: `${BRETAGNE}-d5-a0`,
    day_id: `${BRETAGNE}-d5`,
    time: '09:00',
    title: 'Cap Fréhel — landes et falaises',
    subtitle: '70 m de hauteur · vue jusqu\'aux îles anglo-normandes par beau temps',
    category: 'nature',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d5-a1`,
    day_id: `${BRETAGNE}-d5`,
    time: '11:00',
    title: 'Fort La Latte',
    subtitle: 'Château médiéval sur éperon rocheux · Sam lit le panneau histoire sans qu\'on lui demande',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d5-a2`,
    day_id: `${BRETAGNE}-d5`,
    time: '13:30',
    title: 'Crêperie Ty Breiz',
    subtitle: 'Galette complète + bolée de cidre · glace boule vanille pour les ados',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d5-a3`,
    day_id: `${BRETAGNE}-d5`,
    time: '15:30',
    title: 'Plage de Sables-d\'Or-les-Pins',
    subtitle: 'Grande plage de sable doré · Inès attaque la collection de coques',
    category: 'nature',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── J6 : Saint-Malo intra-muros + plage du Sillon ─────────────────────────
  {
    id: `${BRETAGNE}-d6-a0`,
    day_id: `${BRETAGNE}-d6`,
    time: '09:00',
    title: 'Tour des remparts de Saint-Malo',
    subtitle: '1h30 · vue sur mer + Fort National · Sam en profite pour courir',
    category: 'sport',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d6-a1`,
    day_id: `${BRETAGNE}-d6`,
    time: '11:00',
    title: 'Visite intra-muros',
    subtitle: 'Ruelles médiévales · Malouinière · Château-Musée',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d6-a2`,
    day_id: `${BRETAGNE}-d6`,
    time: '13:00',
    title: 'Déjeuner Chez Lucette',
    subtitle: 'Fruits de mer + galettes saucisse · restaurant familial intra-muros',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d6-a3`,
    day_id: `${BRETAGNE}-d6`,
    time: '15:30',
    title: 'Plage du Sillon',
    subtitle: 'Grande plage de sable fin · Inès fait des châteaux, Sam cherche des vagues',
    category: 'nature',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d6-a4`,
    day_id: `${BRETAGNE}-d6`,
    time: '18:30',
    title: 'Glaces Sanchez',
    subtitle: 'Artisan glacier intra-muros · Inès prend caramel-beurre salé, Sam prend deux boules',
    category: 'food',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── J7 : Dinan médiéval + retour ──────────────────────────────────────────
  {
    id: `${BRETAGNE}-d7-a0`,
    day_id: `${BRETAGNE}-d7`,
    time: '09:30',
    title: 'Vieille ville de Dinan',
    subtitle: 'Maisons à colombages du XVe · Lina liste les restos pour la prochaine fois',
    category: 'culture',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d7-a1`,
    day_id: `${BRETAGNE}-d7`,
    time: '11:00',
    title: 'Château de Dinan',
    subtitle: 'Tour de l\'Horloge + musée · Sam connaît déjà Du Guesclin grâce à la visite',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d7-a2`,
    day_id: `${BRETAGNE}-d7`,
    time: '13:00',
    title: 'Crêperie Ahna',
    subtitle: 'Dernière galette du séjour · Inès prend la crêpe Nutella-banane',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-d7-a3`,
    day_id: `${BRETAGNE}-d7`,
    time: '15:00',
    title: 'Check-out gîte + retour',
    subtitle: 'Coffre de voiture × 4 valises + collection de coquillages d\'Inès',
    category: 'activity',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Completions ─────────────────────────────────────────────────────────────
// Voyage à venir — aucune activité cochée
export const bretagneCompletions: LocalActivityCompletion[] = []

// ─── Spots ───────────────────────────────────────────────────────────────────
export const bretagneSpots: LocalSpot[] = [
  {
    id: `${BRETAGNE}-s1`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Gîte Les Hortensias',
    description: 'Maison bretonne 4 chambres avec jardin, à 10 min à pied de la plage',
    category: 'accommodation',
    zone: 'Perros-Guirec',
    lat: 48.7964,
    lng: -3.4427,
    price: '110€/nuit',
    tags: ['gîte', 'jardin', 'famille'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s2`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Plage de Trestraou',
    description: 'Grande plage de sable fin, idéale pour les enfants, eau surveillée',
    category: 'nature',
    zone: 'Perros-Guirec',
    lat: 48.7994,
    lng: -3.4364,
    price: null,
    tags: ['plage', 'surveillance', 'famille'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s3`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Sentier des Douaniers — Ploumanac\'h',
    description: 'Sentier côtier entre chaos de granit rose, 7 km, tous niveaux',
    category: 'nature',
    zone: 'Ploumanac\'h',
    lat: 48.8317,
    lng: -3.4847,
    price: null,
    tags: ['rando', 'granit rose', 'famille'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s4`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Phare de Mean Ruz',
    description: 'Phare rouge au milieu des rochers roses, emblème de Ploumanac\'h',
    category: 'culture',
    zone: 'Ploumanac\'h',
    lat: 48.8361,
    lng: -3.4933,
    price: null,
    tags: ['phare', 'photo'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s5`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Île de Bréhat',
    description: 'Île sans voitures couverte de fleurs, traversée en vedette depuis l\'Arcouest',
    category: 'nature',
    zone: 'Bréhat',
    lat: 48.8439,
    lng: -3.0044,
    price: 'Vedette ~10€/adulte · ~7€/enfant',
    tags: ['île', 'sans voitures', 'famille'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s6`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Marché de Roscoff',
    description: 'Marché du mardi matin, producteurs locaux, oignons roses AOP',
    category: 'food',
    zone: 'Roscoff',
    lat: 48.7256,
    lng: -3.9831,
    price: null,
    tags: ['marché', 'local', 'mardi'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s7`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Château de Tonquédec',
    description: 'Ruines médiévales du XIVe siècle, accès libre dans la végétation',
    category: 'culture',
    zone: 'Lannion',
    lat: 48.6306,
    lng: -3.4286,
    price: '3€/adulte · gratuit -12 ans',
    tags: ['château', 'ruines', 'aventure enfants'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s8`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Cap Fréhel',
    description: 'Falaises de 70 m, landes de bruyère, vue sur les îles anglo-normandes',
    category: 'nature',
    zone: 'Cap Fréhel',
    lat: 48.6825,
    lng: -2.3167,
    price: 'parking 5€',
    tags: ['falaises', 'panorama', 'landes'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s9`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Fort La Latte',
    description: 'Château médiéval sur éperon rocheux dominant la mer, XVIe siècle',
    category: 'culture',
    zone: 'Cap Fréhel',
    lat: 48.6797,
    lng: -2.2994,
    price: '8€/adulte · 5€ enfant',
    tags: ['château', 'fortification', 'histoire'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s10`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Remparts de Saint-Malo',
    description: 'Tour complet des remparts, 1h30 de marche avec vues sur la mer',
    category: 'culture',
    zone: 'Saint-Malo',
    lat: 48.6494,
    lng: -2.0260,
    price: 'libre',
    tags: ['remparts', 'intra-muros', 'vue mer'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s11`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Plage du Sillon',
    description: 'Longue plage de sable à 5 min des remparts, très animée en été',
    category: 'nature',
    zone: 'Saint-Malo',
    lat: 48.6519,
    lng: -2.0153,
    price: null,
    tags: ['plage', 'sable', 'famille'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s12`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Crêperie Ahna — Dinan',
    description: 'Crêperie dans une maison à colombages du XVe, galettes au sarrasin local',
    category: 'food',
    zone: 'Dinan',
    lat: 48.4547,
    lng: -2.0492,
    price: '10-14€/galette',
    tags: ['crêperie', 'sarrasin', 'famille'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s13`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Crêperie du Port — Perros-Guirec',
    description: 'Adresse locale vue sur le port, galettes complètes et kouign-amann maison',
    category: 'food',
    zone: 'Perros-Guirec',
    lat: 48.7958,
    lng: -3.4447,
    price: '11-15€/galette',
    tags: ['crêperie', 'famille', 'vue port'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s14`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Mini-golf de Trestraou',
    description: '18 trous face à la mer, parfait pour les enfants, géré par la mairie',
    category: 'activity',
    zone: 'Perros-Guirec',
    lat: 48.7999,
    lng: -3.4352,
    price: '5€/adulte · 4€ enfant',
    tags: ['mini-golf', 'enfants', 'vue mer'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-s15`,
    trip_id: BRETAGNE,
    day_id: null,
    name: 'Château de Dinan',
    description: 'Tour de l\'Horloge et musée retraçant l\'histoire de la ville médiévale',
    category: 'culture',
    zone: 'Dinan',
    lat: 48.4528,
    lng: -2.0475,
    price: '5,50€/adulte · 3€ enfant',
    tags: ['château', 'musée', 'médiéval'],
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Expenses ─────────────────────────────────────────────────────────────────
export const bretagneExpenses: LocalExpense[] = [
  // Hébergement
  {
    id: `${BRETAGNE}-e1`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 77000,
    currency: 'EUR',
    category: 'hotel',
    note: 'Gîte Les Hortensias · 7 nuits · 110€/nuit',
    spent_at: '2026-06-15T10:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  // Transport
  {
    id: `${BRETAGNE}-e2`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 18600,
    currency: 'EUR',
    category: 'transport',
    note: 'Essence + péages aller-retour',
    spent_at: '2026-08-08T08:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e3`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 5200,
    currency: 'EUR',
    category: 'transport',
    note: 'Vedette Bréhat A/R × 4 (2 adultes + 2 enfants)',
    spent_at: '2026-08-10T08:30:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  // Activités
  {
    id: `${BRETAGNE}-e4`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 1800,
    currency: 'EUR',
    category: 'activity',
    note: 'Mini-golf Trestraou × 4',
    spent_at: '2026-08-08T18:30:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e5`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 3200,
    currency: 'EUR',
    category: 'activity',
    note: 'Location vélos × 4 (demi-journée)',
    spent_at: '2026-08-09T15:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e6`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 2400,
    currency: 'EUR',
    category: 'activity',
    note: 'Château de Tonquédec × 2 adultes',
    spent_at: '2026-08-11T15:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e7`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 5200,
    currency: 'EUR',
    category: 'activity',
    note: 'Fort La Latte × 2 adultes + 2 enfants',
    spent_at: '2026-08-12T11:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  // Repas — crêperies et restos
  {
    id: `${BRETAGNE}-e8`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 4800,
    currency: 'EUR',
    category: 'food',
    note: 'Crêperie du Port · galettes × 4 + boissons',
    spent_at: '2026-08-08T13:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e9`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 5600,
    currency: 'EUR',
    category: 'food',
    note: 'La Clarté crêperie · galettes + kouign-amann + cidre',
    spent_at: '2026-08-09T19:30:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e10`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 7400,
    currency: 'EUR',
    category: 'food',
    note: 'La Vieille Auberge Bréhat · poisson du jour × 4',
    spent_at: '2026-08-10T12:30:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e11`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 6200,
    currency: 'EUR',
    category: 'food',
    note: 'L\'Écume des Jours · moules frites × 4 + cidre',
    spent_at: '2026-08-11T13:30:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e12`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 5200,
    currency: 'EUR',
    category: 'food',
    note: 'Ty Breiz · galettes + glaces × 4',
    spent_at: '2026-08-12T13:30:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e13`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 7800,
    currency: 'EUR',
    category: 'food',
    note: 'Chez Lucette Saint-Malo · fruits de mer + galettes × 4',
    spent_at: '2026-08-13T13:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e14`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 1200,
    currency: 'EUR',
    category: 'food',
    note: 'Glaces Sanchez × 4 boules (bonus pour Sam)',
    spent_at: '2026-08-13T18:30:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e15`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 5400,
    currency: 'EUR',
    category: 'food',
    note: 'Crêperie Ahna Dinan · galettes × 4 + cidres',
    spent_at: '2026-08-14T13:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  // Courses / marchés
  {
    id: `${BRETAGNE}-e16`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 8600,
    currency: 'EUR',
    category: 'food',
    note: 'Supérette + courses pique-niques (3 jours)',
    spent_at: '2026-08-08T17:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e17`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 3400,
    currency: 'EUR',
    category: 'food',
    note: 'Marché Roscoff · légumes + poissons fumés + crêpes dentelle',
    spent_at: '2026-08-11T09:30:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  // Parkings
  {
    id: `${BRETAGNE}-e18`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 2800,
    currency: 'EUR',
    category: 'transport',
    note: 'Parkings Cap Fréhel + Fort La Latte',
    spent_at: '2026-08-12T09:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  // Shopping / souvenirs
  {
    id: `${BRETAGNE}-e19`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 3600,
    currency: 'EUR',
    category: 'shopping',
    note: 'Souvenirs Saint-Malo · magnets + livres ados + postcards',
    spent_at: '2026-08-13T16:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e20`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 2200,
    currency: 'EUR',
    category: 'shopping',
    note: 'Jardin exotique Roscoff · entrées × 4',
    spent_at: '2026-08-11T11:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e21`,
    trip_id: BRETAGNE,
    payer_id: DEMO_USER_ID,
    amount: 4400,
    currency: 'EUR',
    category: 'activity',
    note: 'Château de Dinan × 2 adultes + 2 enfants',
    spent_at: '2026-08-14T11:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-e22`,
    trip_id: BRETAGNE,
    payer_id: DEMO_PARTNER_ID,
    amount: 1800,
    currency: 'EUR',
    category: 'food',
    note: 'Barbecue gîte J1 · viandes + légumes',
    spent_at: '2026-08-08T19:00:00Z',
    split_mode: 'custom',
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Expense Splits ───────────────────────────────────────────────────────────
// Logique famille :
//   - Location gîte : 1/4 chacun (4 personnes)
//   - Essence/péages : Lina + Tom 0.5 chacun (ados ne conduisent pas)
//   - Restos familiaux : 0.30 Lina / 0.30 Tom / 0.20 Sam / 0.20 Inès
//   - Activités enfants incluses : 0.25 chacun
//   - Activités adultes uniquement : 0.5 chacun
export const bretagneSplits: LocalExpenseSplit[] = [
  // e1 — gîte : 1/4 chacun
  { expense_id: `${BRETAGNE}-e1`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e1`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e1`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e1`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e2 — essence : Lina + Tom 0.5
  { expense_id: `${BRETAGNE}-e2`, user_id: DEMO_USER_ID,    share: 0.5 },
  { expense_id: `${BRETAGNE}-e2`, user_id: DEMO_PARTNER_ID, share: 0.5 },
  // e3 — vedette Bréhat : 1/4 chacun
  { expense_id: `${BRETAGNE}-e3`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e3`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e3`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e3`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e4 — mini-golf : 1/4 chacun
  { expense_id: `${BRETAGNE}-e4`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e4`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e4`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e4`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e5 — vélos : 1/4 chacun
  { expense_id: `${BRETAGNE}-e5`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e5`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e5`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e5`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e6 — Tonquédec adultes seulement : 0.5 / 0.5
  { expense_id: `${BRETAGNE}-e6`, user_id: DEMO_USER_ID,    share: 0.5 },
  { expense_id: `${BRETAGNE}-e6`, user_id: DEMO_PARTNER_ID, share: 0.5 },
  // e7 — Fort La Latte : 1/4 chacun
  { expense_id: `${BRETAGNE}-e7`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e7`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e7`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e7`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e8 — crêperie port : resto famille 0.30/0.30/0.20/0.20
  { expense_id: `${BRETAGNE}-e8`, user_id: DEMO_USER_ID,    share: 0.30 },
  { expense_id: `${BRETAGNE}-e8`, user_id: DEMO_PARTNER_ID, share: 0.30 },
  { expense_id: `${BRETAGNE}-e8`, user_id: DEMO_SAM_ID,     share: 0.20 },
  { expense_id: `${BRETAGNE}-e8`, user_id: DEMO_INES_ID,    share: 0.20 },
  // e9 — La Clarté : resto famille 0.30/0.30/0.20/0.20
  { expense_id: `${BRETAGNE}-e9`, user_id: DEMO_USER_ID,    share: 0.30 },
  { expense_id: `${BRETAGNE}-e9`, user_id: DEMO_PARTNER_ID, share: 0.30 },
  { expense_id: `${BRETAGNE}-e9`, user_id: DEMO_SAM_ID,     share: 0.20 },
  { expense_id: `${BRETAGNE}-e9`, user_id: DEMO_INES_ID,    share: 0.20 },
  // e10 — Bréhat resto : 0.30/0.30/0.20/0.20
  { expense_id: `${BRETAGNE}-e10`, user_id: DEMO_USER_ID,    share: 0.30 },
  { expense_id: `${BRETAGNE}-e10`, user_id: DEMO_PARTNER_ID, share: 0.30 },
  { expense_id: `${BRETAGNE}-e10`, user_id: DEMO_SAM_ID,     share: 0.20 },
  { expense_id: `${BRETAGNE}-e10`, user_id: DEMO_INES_ID,    share: 0.20 },
  // e11 — moules frites : 0.30/0.30/0.20/0.20
  { expense_id: `${BRETAGNE}-e11`, user_id: DEMO_USER_ID,    share: 0.30 },
  { expense_id: `${BRETAGNE}-e11`, user_id: DEMO_PARTNER_ID, share: 0.30 },
  { expense_id: `${BRETAGNE}-e11`, user_id: DEMO_SAM_ID,     share: 0.20 },
  { expense_id: `${BRETAGNE}-e11`, user_id: DEMO_INES_ID,    share: 0.20 },
  // e12 — Ty Breiz : 0.30/0.30/0.20/0.20
  { expense_id: `${BRETAGNE}-e12`, user_id: DEMO_USER_ID,    share: 0.30 },
  { expense_id: `${BRETAGNE}-e12`, user_id: DEMO_PARTNER_ID, share: 0.30 },
  { expense_id: `${BRETAGNE}-e12`, user_id: DEMO_SAM_ID,     share: 0.20 },
  { expense_id: `${BRETAGNE}-e12`, user_id: DEMO_INES_ID,    share: 0.20 },
  // e13 — Chez Lucette : 0.30/0.30/0.20/0.20
  { expense_id: `${BRETAGNE}-e13`, user_id: DEMO_USER_ID,    share: 0.30 },
  { expense_id: `${BRETAGNE}-e13`, user_id: DEMO_PARTNER_ID, share: 0.30 },
  { expense_id: `${BRETAGNE}-e13`, user_id: DEMO_SAM_ID,     share: 0.20 },
  { expense_id: `${BRETAGNE}-e13`, user_id: DEMO_INES_ID,    share: 0.20 },
  // e14 — glaces : 1/4 chacun
  { expense_id: `${BRETAGNE}-e14`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e14`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e14`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e14`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e15 — Ahna Dinan : 0.30/0.30/0.20/0.20
  { expense_id: `${BRETAGNE}-e15`, user_id: DEMO_USER_ID,    share: 0.30 },
  { expense_id: `${BRETAGNE}-e15`, user_id: DEMO_PARTNER_ID, share: 0.30 },
  { expense_id: `${BRETAGNE}-e15`, user_id: DEMO_SAM_ID,     share: 0.20 },
  { expense_id: `${BRETAGNE}-e15`, user_id: DEMO_INES_ID,    share: 0.20 },
  // e16 — courses : 1/4 chacun
  { expense_id: `${BRETAGNE}-e16`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e16`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e16`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e16`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e17 — marché Roscoff : 1/4 chacun
  { expense_id: `${BRETAGNE}-e17`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e17`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e17`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e17`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e18 — parkings : Lina + Tom 0.5
  { expense_id: `${BRETAGNE}-e18`, user_id: DEMO_USER_ID,    share: 0.5 },
  { expense_id: `${BRETAGNE}-e18`, user_id: DEMO_PARTNER_ID, share: 0.5 },
  // e19 — souvenirs : 0.30/0.30/0.20/0.20
  { expense_id: `${BRETAGNE}-e19`, user_id: DEMO_USER_ID,    share: 0.30 },
  { expense_id: `${BRETAGNE}-e19`, user_id: DEMO_PARTNER_ID, share: 0.30 },
  { expense_id: `${BRETAGNE}-e19`, user_id: DEMO_SAM_ID,     share: 0.20 },
  { expense_id: `${BRETAGNE}-e19`, user_id: DEMO_INES_ID,    share: 0.20 },
  // e20 — jardin exotique : 1/4 chacun
  { expense_id: `${BRETAGNE}-e20`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e20`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e20`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e20`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e21 — Château Dinan : 1/4 chacun
  { expense_id: `${BRETAGNE}-e21`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e21`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e21`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e21`, user_id: DEMO_INES_ID,    share: 0.25 },
  // e22 — barbecue gîte : 1/4 chacun
  { expense_id: `${BRETAGNE}-e22`, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: `${BRETAGNE}-e22`, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: `${BRETAGNE}-e22`, user_id: DEMO_SAM_ID,     share: 0.25 },
  { expense_id: `${BRETAGNE}-e22`, user_id: DEMO_INES_ID,    share: 0.25 },
]

// ─── Checklist ────────────────────────────────────────────────────────────────
export const bretagneChecklist: LocalChecklistItem[] = [
  { id: `${BRETAGNE}-c1`,  trip_id: BRETAGNE, label: 'Maillots de bain × 4 (prévoir 2 par enfant)',  category: 'clothing', position: 0,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c2`,  trip_id: BRETAGNE, label: 'Brassards + bouée Inès',                       category: 'gear',     position: 1,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c3`,  trip_id: BRETAGNE, label: 'Jeux de plage (raquettes, ballon, seau/râteau)', category: 'gear',   position: 2,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c4`,  trip_id: BRETAGNE, label: 'Crème solaire indice 50 × 2 grandes bouteilles', category: 'gear',  position: 3,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c5`,  trip_id: BRETAGNE, label: 'Kits pluie — K-ways × 4 (Bretagne oblige !)',  category: 'clothing', position: 4,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c6`,  trip_id: BRETAGNE, label: 'Chaussures de marche × 4 (sentier douaniers)', category: 'clothing', position: 5,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c7`,  trip_id: BRETAGNE, label: 'Réserver gîte Les Hortensias',                 category: 'docs',     position: 6,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c8`,  trip_id: BRETAGNE, label: 'Réserver vedette Bréhat (peak août, tôt !)',   category: 'docs',     position: 7,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c9`,  trip_id: BRETAGNE, label: 'Carte routière Bretagne + topo littoral',      category: 'gear',     position: 8,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c10`, trip_id: BRETAGNE, label: 'Livres ados (Sam : roman SF, Inès : BD)',      category: 'other',    position: 9,  created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c11`, trip_id: BRETAGNE, label: 'Cartes vitales + assurance voyage famille',    category: 'docs',     position: 10, created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c12`, trip_id: BRETAGNE, label: 'Application Tables des marées Bretagne',       category: 'other',    position: 11, created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c13`, trip_id: BRETAGNE, label: 'Glacière + boissons pour routes + plages',     category: 'gear',     position: 12, created_at: NOW, updated_at: NOW },
  { id: `${BRETAGNE}-c14`, trip_id: BRETAGNE, label: 'Trousse pharmacie (pansements, antiseptique)', category: 'gear',     position: 13, created_at: NOW, updated_at: NOW },
]

// 6 items cochés par Lina (la planificatrice)
export const bretagneChecklistDone: LocalChecklistCompletion[] = [
  'c7', 'c8', 'c11', 'c1', 'c4', 'c12',
].map((c) => ({
  item_id: `${BRETAGNE}-${c}`,
  user_id: DEMO_USER_ID,
  completed_at: '2026-05-21T09:00:00Z',
}))

// ─── Guide Cards ──────────────────────────────────────────────────────────────
export const bretagneGuide: LocalGuideCard[] = [
  {
    id: `${BRETAGNE}-g1`,
    trip_id: BRETAGNE,
    kind: 'weather',
    title: 'Météo Bretagne — l\'imprévisible',
    body: 'Même en août, une journée ensoleillée peut virer à l\'averse en 2h. Toujours un K-way dans le sac. La règle : 4 saisons en une journée, prévoir en conséquence.',
    icon_name: 'Cloud',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-g2`,
    trip_id: BRETAGNE,
    kind: 'info',
    title: 'Marées — coefficients forts',
    body: 'La Bretagne a des coefficients de marée parmi les plus élevés d\'Europe (jusqu\'à 120). Vérifier les horaires avant chaque plage — certaines disparaissent à marée haute. App "Météo Bretagne" ou "Tides" recommandée.',
    icon_name: 'Waves',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-g3`,
    trip_id: BRETAGNE,
    kind: 'emergency',
    title: 'Urgences avec enfants',
    body: 'CHU Brest : 02 98 22 33 33 · CH Saint-Brieuc : 02 96 01 71 23 · SAMU : 15 · Garde côtes (noyade) : 196. Préférer les plages surveillées (drapeau vert) avec enfants.',
    icon_name: 'Flame',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-g4`,
    trip_id: BRETAGNE,
    kind: 'food',
    title: 'Crêperies — le guide de survie',
    body: 'Galette = sarrasin + salé (complète = jambon/œuf/fromage, ~11€). Crêpe = froment + sucré. Cidre breton classique en bolée. Éviter les crêperies face aux parkings touristiques — chercher à 2 rues de là.',
    icon_name: 'UtensilsCrossed',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${BRETAGNE}-g5`,
    trip_id: BRETAGNE,
    kind: 'warning',
    title: 'Sécurité plage avec enfants',
    body: 'Courants en Bretagne peuvent être forts même sur sable. Baigner les enfants uniquement entre les drapeaux rouges (zone surveillée). Brassards pour Inès obligatoires. Surveiller les rochers glissants sur le sentier des douaniers.',
    icon_name: 'AlertTriangle',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },
]
