// lib/demo/fixtures-skatepark.ts — Voyage démo : road trip skateparks Pays Basque / Sud-Ouest.
//
// 4 potes (Camille, Lina, Tom, Yanis) · van chargé de planches · 5 jours · juillet 2026
// Anglet → Hossegor → Capbreton → Mimizan → Biscarrosse → Bordeaux
//
// ID du voyage : 'demo-trip-skatepark'
// Owner : Camille (organisatrice)
// Statut : à venir → completions vides, checklist partiellement cochée

import type {
  LocalTrip,
  LocalTripMember,
  LocalDay,
  LocalActivity,
  LocalActivityCompletion,
  LocalSpot,
  LocalExpense,
  LocalExpenseSplit,
  LocalChecklistItem,
  LocalChecklistCompletion,
  LocalGuideCard,
} from '@/lib/db/schema'

import {
  DEMO_USER_ID,
  DEMO_PARTNER_ID,
  DEMO_CAMILLE_ID,
  DEMO_YANIS_ID,
} from './ids'

const NOW = new Date('2026-05-21T10:00:00Z').toISOString()
const SK = 'demo-trip-skatepark'

// ─── Trip ────────────────────────────────────────────────────────────────────
export const skateparkTrip: LocalTrip = {
  id: SK,
  owner_id: DEMO_CAMILLE_ID,
  name: 'Tour des bowls SO',
  destination: 'Anglet → Bordeaux',
  start_date: '2026-07-04',
  end_date: '2026-07-08',
  trip_type: 'sport',
  currency: 'EUR',
  total_budget: 850,
  cover_color: '#B14E32',
  join_code: 'MKT-DEMO4',
  hero_image_url: '/heroes/sport/1.jpg',
  hero_image_uploaded: false,
  created_at: NOW,
  updated_at: NOW,
}

// ─── Members ─────────────────────────────────────────────────────────────────
export const skateparkMembers: LocalTripMember[] = [
  { trip_id: SK, user_id: DEMO_CAMILLE_ID, role: 'owner', joined_at: NOW },
  { trip_id: SK, user_id: DEMO_USER_ID,    role: 'editor', joined_at: NOW },
  { trip_id: SK, user_id: DEMO_PARTNER_ID, role: 'editor', joined_at: NOW },
  { trip_id: SK, user_id: DEMO_YANIS_ID,   role: 'editor', joined_at: NOW },
]

// ─── Days ─────────────────────────────────────────────────────────────────────
export const skateparkDays: LocalDay[] = [
  {
    id: `${SK}-d1`,
    trip_id: SK,
    day_number: 1,
    date: '2026-07-04',
    label: 'Jour 1',
    theme: 'Anglet · Skatepark de la Barre',
    zone: 'Anglet',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d2`,
    trip_id: SK,
    day_number: 2,
    date: '2026-07-05',
    label: 'Jour 2',
    theme: 'Hossegor → Capbreton',
    zone: 'Hossegor',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d3`,
    trip_id: SK,
    day_number: 3,
    date: '2026-07-06',
    label: 'Jour 3',
    theme: 'Route Landaise · Mimizan + Biscarrosse',
    zone: 'Landes',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d4`,
    trip_id: SK,
    day_number: 4,
    date: '2026-07-07',
    label: 'Jour 4',
    theme: 'Bordeaux · Cité Saint-Michel + Quais',
    zone: 'Bordeaux',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d5`,
    trip_id: SK,
    day_number: 5,
    date: '2026-07-08',
    label: 'Jour 5',
    theme: 'Bordeaux · Skate shops + retour',
    zone: 'Bordeaux',
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Activities (~26 au total) ────────────────────────────────────────────────
export const skateparkActivities: LocalActivity[] = [
  // ── Jour 1 — Anglet (6 activités) ──────────────────────────────────────────
  {
    id: `${SK}-d1-a0`,
    day_id: `${SK}-d1`,
    time: '07:30',
    title: 'Départ Paris · van chargé',
    subtitle: 'Coffre : 4 decks, roues de rechange, glacière + packs de San Pel',
    category: 'activity',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d1-a1`,
    day_id: `${SK}-d1`,
    time: '14:00',
    title: 'Arrivée Anglet · check-in appart',
    subtitle: 'Airbnb Résidence de la Plage — 2 chambres, terrasse, parking van ok',
    category: 'accommodation',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d1-a2`,
    day_id: `${SK}-d1`,
    time: '15:30',
    title: 'Skatepark de la Barre',
    subtitle: 'Bowl historique d\'Anglet — free, béton lisse, vue océan à 200m',
    category: 'sport',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d1-a3`,
    day_id: `${SK}-d1`,
    time: '18:00',
    title: 'Boardriders HQ Campus',
    subtitle: 'Siège Quiksilver/Roxy à deux pas — boutique outlet, on lèche les vitrines',
    category: 'culture',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d1-a4`,
    day_id: `${SK}-d1`,
    time: '19:30',
    title: 'Plage des Cavaliers — coucher de soleil',
    subtitle: 'On pose les planches, les pieds dans le sable. Premier apéro du trip.',
    category: 'nature',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d1-a5`,
    day_id: `${SK}-d1`,
    time: '21:00',
    title: 'Dîner — Le Surfing',
    subtitle: 'Burgers oignons caramélisés + bière basque. Terrasse de ouf.',
    category: 'food',
    position: 5,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── Jour 2 — Hossegor → Capbreton (5 activités) ────────────────────────────
  {
    id: `${SK}-d2-a0`,
    day_id: `${SK}-d2`,
    time: '09:00',
    title: 'Session matinale — Hossegor plage',
    subtitle: 'Pas de skate — baignade et marée basse. Se réveiller doucement.',
    category: 'nature',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d2-a1`,
    day_id: `${SK}-d2`,
    time: '11:00',
    title: 'Skatepark de Hossegor',
    subtitle: 'Rue du Pic du Midi — street + mini-ramp. Béton correct, souvent du monde.',
    category: 'sport',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d2-a2`,
    day_id: `${SK}-d2`,
    time: '13:30',
    title: 'Déjeuner — Chez Belhara',
    subtitle: 'Poke bowl thon et gambas grillées. Terrasse face au lac.',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d2-a3`,
    day_id: `${SK}-d2`,
    time: '15:30',
    title: 'Skatepark de Capbreton',
    subtitle: 'Bowl profond 2m40, transitions arrondies. Yanis va kiffer le coping.',
    category: 'sport',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d2-a4`,
    day_id: `${SK}-d2`,
    time: '20:30',
    title: 'Bivouac parking Capbreton',
    subtitle: 'Van, sacs de couchage, playlist lo-fi. Économie de nuit.',
    category: 'accommodation',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── Jour 3 — Route Landaise (5 activités) ──────────────────────────────────
  {
    id: `${SK}-d3-a0`,
    day_id: `${SK}-d3`,
    time: '08:30',
    title: 'Café + croissants à Mimizan-Plage',
    subtitle: 'Boulangerie Duprat — les meilleures viennoiseries de la côte landaise',
    category: 'food',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d3-a1`,
    day_id: `${SK}-d3`,
    time: '10:00',
    title: 'Skatepark de Mimizan',
    subtitle: 'Spot underrated. Bowls de 2 tailles, pas grand monde en semaine.',
    category: 'sport',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d3-a2`,
    day_id: `${SK}-d3`,
    time: '13:00',
    title: 'Lac de Biscarrosse · baignade',
    subtitle: 'Pause kiff au bord du lac — les genoux remercient après les bowls.',
    category: 'nature',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d3-a3`,
    day_id: `${SK}-d3`,
    time: '15:30',
    title: 'Skatepark de Biscarrosse',
    subtitle: 'Nouveau spot refait en 2024. Full street : ledges, rails, escalier 5.',
    category: 'sport',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d3-a4`,
    day_id: `${SK}-d3`,
    time: '19:00',
    title: 'Route vers Bordeaux',
    subtitle: 'On double l\'A63. Podcast Boardroom dans le van.',
    category: 'activity',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── Jour 4 — Bordeaux Saint-Michel + Quais (5 activités) ───────────────────
  {
    id: `${SK}-d4-a0`,
    day_id: `${SK}-d4`,
    time: '09:30',
    title: 'Check-in auberge Cité Saint-Michel',
    subtitle: '4 lits en dortoir privé — douches, casiers. On pose les decks.',
    category: 'accommodation',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d4-a1`,
    day_id: `${SK}-d4`,
    time: '11:00',
    title: 'Skatepark des Quais — Bordeaux',
    subtitle: 'Spot légendaire en bord de Garonne. Bowl + street. Se remplit vite l\'aprèm.',
    category: 'sport',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d4-a2`,
    day_id: `${SK}-d4`,
    time: '13:30',
    title: 'Marché des Capucins — déjeuner',
    subtitle: 'Huîtres du Bassin + saucisson basque. Camille paye le vin blanc.',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d4-a3`,
    day_id: `${SK}-d4`,
    time: '16:00',
    title: 'Darwin Bordeaux — Bowl intérieur',
    subtitle: 'Ancienne caserne réhabilitée. Skatepark indoor + resto + brasserie. Vibes.',
    category: 'sport',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d4-a4`,
    day_id: `${SK}-d4`,
    time: '20:30',
    title: 'Dîner — La Brasserie Darwin',
    subtitle: 'Burgers & planches de charcuterie. On refait le match des tricks du jour.',
    category: 'food',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── Jour 5 — Skate shops + retour (5 activités) ────────────────────────────
  {
    id: `${SK}-d5-a0`,
    day_id: `${SK}-d5`,
    time: '10:00',
    title: 'Skate shop Bordeaux — Yakuza Skateshop',
    subtitle: 'Decks, trucks, roues. Tom s\'achète une Quasi. Yanis commande des roulements.',
    category: 'culture',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d5-a1`,
    day_id: `${SK}-d5`,
    time: '12:00',
    title: 'Déjeuner rue Sainte-Catherine',
    subtitle: 'Sandwich banh-mi au Nem + café allongé pour tenir la route.',
    category: 'food',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d5-a2`,
    day_id: `${SK}-d5`,
    time: '13:30',
    title: 'Session street final — place de la Victoire',
    subtitle: 'Dernière run informelle. Camille se lâche sur la colonne. Spots bonus.',
    category: 'sport',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d5-a3`,
    day_id: `${SK}-d5`,
    time: '15:30',
    title: 'Retour van · Bordeaux → Paris',
    subtitle: 'On rentre avec des genoux en vrac, des sourires et trop de vidéos à monter.',
    category: 'activity',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-d5-a4`,
    day_id: `${SK}-d5`,
    time: '22:00',
    title: 'Arrivée Paris · débrief glacière',
    subtitle: 'Reste 2 bières landaises. On les finit dans le parking. Prochain trip : Barcelone?',
    category: 'nightlife',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Activity Completions (vide — voyage à venir) ─────────────────────────────
export const skateparkCompletions: LocalActivityCompletion[] = []

// ─── Spots (12) ───────────────────────────────────────────────────────────────
export const skateparkSpots: LocalSpot[] = [
  {
    id: `${SK}-s1`,
    trip_id: SK,
    day_id: null,
    name: 'Skatepark de la Barre — Anglet',
    description: 'Bowl historique bétonné, gratuit, ouvert 24h. Vent marin, ambiance unique.',
    category: 'sport',
    zone: 'Anglet',
    lat: 43.5143,
    lng: -1.5457,
    price: 'gratuit',
    tags: ['bowl', 'free', 'historique'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s2`,
    trip_id: SK,
    day_id: null,
    name: 'Boardriders HQ Campus — Anglet',
    description: 'Campus Quiksilver/Roxy, outlet shop, architecture bois et métal. Incontournable.',
    category: 'activity',
    zone: 'Anglet',
    lat: 43.5082,
    lng: -1.5419,
    price: 'libre',
    tags: ['outlet', 'surf', 'skate'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s3`,
    trip_id: SK,
    day_id: null,
    name: 'Plage des Cavaliers — Anglet',
    description: 'Une des 11 plages d\'Anglet. Moins fréquentée que la Chambre d\'Amour, parfaite pour poser.',
    category: 'nature',
    zone: 'Anglet',
    lat: 43.5215,
    lng: -1.5551,
    price: null,
    tags: ['plage', 'coucher-de-soleil'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s4`,
    trip_id: SK,
    day_id: null,
    name: 'Skatepark de Hossegor',
    description: 'Rue du Pic du Midi. Street course + mini-ramp en bois abrité. Béton granuleux.',
    category: 'sport',
    zone: 'Hossegor',
    lat: 43.6596,
    lng: -1.4147,
    price: 'gratuit',
    tags: ['street', 'mini-ramp'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s5`,
    trip_id: SK,
    day_id: null,
    name: 'Skatepark de Capbreton',
    description: 'Bowl en béton lisse, 2m40 de profondeur. Ambiance locale, copains du coin.',
    category: 'sport',
    zone: 'Capbreton',
    lat: 43.6452,
    lng: -1.4338,
    price: 'gratuit',
    tags: ['bowl', 'deep', 'coping'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s6`,
    trip_id: SK,
    day_id: null,
    name: 'Skatepark de Mimizan',
    description: 'Spot underrated des Landes. Deux bowls imbriqués, revêtement parfait.',
    category: 'sport',
    zone: 'Mimizan',
    lat: 44.2002,
    lng: -1.2286,
    price: 'gratuit',
    tags: ['bowl', 'landes', 'calme'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s7`,
    trip_id: SK,
    day_id: null,
    name: 'Lac de Biscarrosse-Plage',
    description: 'Lac landais, baignade agréable, plage de sable fin. Récupération active.',
    category: 'nature',
    zone: 'Biscarrosse',
    lat: 44.4505,
    lng: -1.1633,
    price: null,
    tags: ['lac', 'baignade', 'détente'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s8`,
    trip_id: SK,
    day_id: null,
    name: 'Skatepark de Biscarrosse',
    description: 'Refait en 2024. Full street layout : escalier 5 marches, ledges marble, rail kink.',
    category: 'sport',
    zone: 'Biscarrosse',
    lat: 44.3942,
    lng: -1.1680,
    price: 'gratuit',
    tags: ['street', 'neuf', 'tech'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s9`,
    trip_id: SK,
    day_id: null,
    name: 'Skatepark des Quais — Bordeaux',
    description: 'Spot légendaire en bord de Garonne. Bowl + modules street. Vue sur le fleuve.',
    category: 'sport',
    zone: 'Bordeaux Quais',
    lat: 44.8378,
    lng: -0.5757,
    price: 'gratuit',
    tags: ['bowl', 'street', 'bord-de-fleuve'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s10`,
    trip_id: SK,
    day_id: null,
    name: 'Darwin Bordeaux — Bowl Indoor',
    description: 'Ancienne caserne Niel reconvertie. Skatepark couvert, brasserie, marché bio le week-end.',
    category: 'sport',
    zone: 'Bordeaux Bastide',
    lat: 44.8384,
    lng: -0.5613,
    price: '5€/session',
    tags: ['indoor', 'bowl', 'brasserie'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s11`,
    trip_id: SK,
    day_id: null,
    name: 'Yakuza Skateshop — Bordeaux',
    description: 'LA référence du skate bordelais. Decks indépendants, trucks Indy, hardware complet.',
    category: 'activity',
    zone: 'Bordeaux Centre',
    lat: 44.8367,
    lng: -0.5776,
    price: 'deck ~80€',
    tags: ['shop', 'local', 'conseil'],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-s12`,
    trip_id: SK,
    day_id: null,
    name: 'Marché des Capucins — Bordeaux',
    description: 'Le ventre de Bordeaux. Huîtres, saucissons, fromages. Vin blanc debout, 10h du mat.',
    category: 'food',
    zone: 'Bordeaux Saint-Michel',
    lat: 44.8322,
    lng: -0.5700,
    price: '15-20€/tête',
    tags: ['marché', 'huitres', 'local'],
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Expenses (18 — montants en centimes) ─────────────────────────────────────
export const skateparkExpenses: LocalExpense[] = [
  // Transport
  {
    id: `${SK}-e1`,
    trip_id: SK,
    payer_id: DEMO_CAMILLE_ID,
    amount: 12000,
    currency: 'EUR',
    category: 'transport',
    note: 'Essence Paris → Anglet (aller, van)',
    spent_at: '2026-07-04T07:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e2`,
    trip_id: SK,
    payer_id: DEMO_YANIS_ID,
    amount: 9800,
    currency: 'EUR',
    category: 'transport',
    note: 'Essence Anglet → Bordeaux + retour',
    spent_at: '2026-07-06T19:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e3`,
    trip_id: SK,
    payer_id: DEMO_CAMILLE_ID,
    amount: 7500,
    currency: 'EUR',
    category: 'transport',
    note: 'Péages autoroute A63 × 4 jours',
    spent_at: '2026-07-04T14:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  // Hébergement
  {
    id: `${SK}-e4`,
    trip_id: SK,
    payer_id: DEMO_CAMILLE_ID,
    amount: 22000,
    currency: 'EUR',
    category: 'hotel',
    note: 'Airbnb Anglet Résidence de la Plage — 2 nuits',
    spent_at: '2026-06-15T10:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e5`,
    trip_id: SK,
    payer_id: DEMO_USER_ID,
    amount: 11200,
    currency: 'EUR',
    category: 'hotel',
    note: 'Auberge Saint-Michel Bordeaux — dortoir privé 2 nuits × 4',
    spent_at: '2026-06-20T14:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  // Nourriture
  {
    id: `${SK}-e6`,
    trip_id: SK,
    payer_id: DEMO_PARTNER_ID,
    amount: 5600,
    currency: 'EUR',
    category: 'food',
    note: 'Dîner Le Surfing · 4 burgers + bières',
    spent_at: '2026-07-04T21:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e7`,
    trip_id: SK,
    payer_id: DEMO_CAMILLE_ID,
    amount: 4800,
    currency: 'EUR',
    category: 'food',
    note: 'Déjeuner Chez Belhara — poke bowls × 4',
    spent_at: '2026-07-05T13:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e8`,
    trip_id: SK,
    payer_id: DEMO_YANIS_ID,
    amount: 1200,
    currency: 'EUR',
    category: 'food',
    note: 'Boulangerie Duprat — croissants + pains au choco × 4',
    spent_at: '2026-07-06T08:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e9`,
    trip_id: SK,
    payer_id: DEMO_USER_ID,
    amount: 6400,
    currency: 'EUR',
    category: 'food',
    note: 'Marché des Capucins — huîtres + vin blanc + charcuterie',
    spent_at: '2026-07-07T13:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e10`,
    trip_id: SK,
    payer_id: DEMO_PARTNER_ID,
    amount: 7200,
    currency: 'EUR',
    category: 'food',
    note: 'Dîner Brasserie Darwin — planches + burgers',
    spent_at: '2026-07-07T20:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e11`,
    trip_id: SK,
    payer_id: DEMO_CAMILLE_ID,
    amount: 2200,
    currency: 'EUR',
    category: 'food',
    note: 'Banh-mi + cafés rue Sainte-Catherine × 4',
    spent_at: '2026-07-08T12:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  // Boissons
  {
    id: `${SK}-e12`,
    trip_id: SK,
    payer_id: DEMO_YANIS_ID,
    amount: 3600,
    currency: 'EUR',
    category: 'drink',
    note: 'Caisse bières landaises Lancelot + San Pellegrino glacière',
    spent_at: '2026-07-03T18:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e13`,
    trip_id: SK,
    payer_id: DEMO_USER_ID,
    amount: 1800,
    currency: 'EUR',
    category: 'drink',
    note: 'Café + jus pression spots roadside × 3 étapes',
    spent_at: '2026-07-06T09:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  // Activités
  {
    id: `${SK}-e14`,
    trip_id: SK,
    payer_id: DEMO_CAMILLE_ID,
    amount: 2000,
    currency: 'EUR',
    category: 'activity',
    note: 'Darwin bowl indoor — entrées × 4',
    spent_at: '2026-07-07T16:00:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  // Shopping skate
  {
    id: `${SK}-e15`,
    trip_id: SK,
    payer_id: DEMO_PARTNER_ID,
    amount: 8500,
    currency: 'EUR',
    category: 'shopping',
    note: 'Tom — Quasi deck + griptape Yakuza Skateshop',
    spent_at: '2026-07-08T10:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e16`,
    trip_id: SK,
    payer_id: DEMO_YANIS_ID,
    amount: 3200,
    currency: 'EUR',
    category: 'shopping',
    note: 'Yanis — roulements Bones Reds × 2 sets + roues Spitfire',
    spent_at: '2026-07-08T10:45:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e17`,
    trip_id: SK,
    payer_id: DEMO_CAMILLE_ID,
    amount: 4500,
    currency: 'EUR',
    category: 'shopping',
    note: 'Lina — T-shirt Boardriders outlet + casquette',
    spent_at: '2026-07-04T18:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-e18`,
    trip_id: SK,
    payer_id: DEMO_USER_ID,
    amount: 3000,
    currency: 'EUR',
    category: 'other',
    note: 'Courses intermarché : pain, fromage, fruits, saucisson route landaise',
    spent_at: '2026-07-06T07:30:00Z',
    split_mode: 'equal',
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Expense Splits (18 × 4 = 72 splits) ──────────────────────────────────────
export const skateparkSplits: LocalExpenseSplit[] = skateparkExpenses.flatMap((e) => [
  { expense_id: e.id, user_id: DEMO_CAMILLE_ID, share: 0.25 },
  { expense_id: e.id, user_id: DEMO_USER_ID,    share: 0.25 },
  { expense_id: e.id, user_id: DEMO_PARTNER_ID, share: 0.25 },
  { expense_id: e.id, user_id: DEMO_YANIS_ID,   share: 0.25 },
])

// ─── Checklist (15 items) ─────────────────────────────────────────────────────
export const skateparkChecklist: LocalChecklistItem[] = [
  { id: `${SK}-c1`,  trip_id: SK, label: 'Skateboards × 4 (decks + trucks + roues ok)', category: 'gear', position: 0,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c2`,  trip_id: SK, label: 'Kit roulements de rechange (Bones Reds)', category: 'gear', position: 1,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c3`,  trip_id: SK, label: 'Casque certifié CE (obligatoire certains spots)', category: 'gear', position: 2,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c4`,  trip_id: SK, label: 'Genouillères + coudières', category: 'gear', position: 3,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c5`,  trip_id: SK, label: 'Sac de couchage léger (bivouac van)', category: 'gear', position: 4,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c6`,  trip_id: SK, label: 'Ice pack / bandages élastiques (genoux)', category: 'gear', position: 5,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c7`,  trip_id: SK, label: 'Crème solaire SPF50 + lèvres', category: 'gear', position: 6,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c8`,  trip_id: SK, label: 'Glacière + accumulateurs de froid', category: 'gear', position: 7,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c9`,  trip_id: SK, label: 'Chargeur 220V pour le van', category: 'gear', position: 8,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c10`, trip_id: SK, label: 'Réserver Airbnb Anglet (Camille)', category: 'docs', position: 9,  created_at: NOW, updated_at: NOW },
  { id: `${SK}-c11`, trip_id: SK, label: 'Réserver auberge Bordeaux (Lina)', category: 'docs', position: 10, created_at: NOW, updated_at: NOW },
  { id: `${SK}-c12`, trip_id: SK, label: 'Carte assurance rapatriement / sport', category: 'docs', position: 11, created_at: NOW, updated_at: NOW },
  { id: `${SK}-c13`, trip_id: SK, label: 'Clé outil skate (Y-tool ou outils séparés)', category: 'gear', position: 12, created_at: NOW, updated_at: NOW },
  { id: `${SK}-c14`, trip_id: SK, label: 'Téléphone : appli Waze + playlist van', category: 'other', position: 13, created_at: NOW, updated_at: NOW },
  { id: `${SK}-c15`, trip_id: SK, label: 'Griptape de rechange × 2 feuilles', category: 'gear', position: 14, created_at: NOW, updated_at: NOW },
]

// 5 items cochés par Camille (organisatrice) — voyage à venir
export const skateparkChecklistDone: LocalChecklistCompletion[] = [
  'c1', 'c3', 'c8', 'c10', 'c11',
].map((c) => ({
  item_id: `${SK}-${c}`,
  user_id: DEMO_CAMILLE_ID,
  completed_at: '2026-05-20T18:00:00Z',
}))

// ─── Guide Cards (5) ──────────────────────────────────────────────────────────
export const skateparkGuide: LocalGuideCard[] = [
  {
    id: `${SK}-g1`,
    trip_id: SK,
    kind: 'danger',
    title: 'Vol de matos sur la plage',
    body: 'Anglet et Hossegor sont connues pour les vols à la roulotte en plein été. Ne jamais laisser decks ou sacs visibles dans le van garé.',
    icon_name: 'ShieldAlert',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-g2`,
    trip_id: SK,
    kind: 'warning',
    title: 'Marées et spots côtiers',
    body: 'Plusieurs spots du Pays Basque sont inaccessibles à marée haute. Consulte les tables de marées (Météo France ou Surf Report) avant de bouger.',
    icon_name: 'Waves',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-g3`,
    trip_id: SK,
    kind: 'info',
    title: 'Spots fermés en juillet',
    body: 'Certains skateparks municipaux ferment le midi (12h-15h) en juillet pour cause de chaleur. Viser les sessions tôt le matin ou après 16h.',
    icon_name: 'Info',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-g4`,
    trip_id: SK,
    kind: 'weather',
    title: 'Météo Atlantique — attention aux coups de vent',
    body: 'La côte landaise peut se couvrir vite. Surveille Windguru la veille. Par vent >30 km/h, les sessions bowl en extérieur deviennent sportives (et risquées).',
    icon_name: 'Wind',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${SK}-g5`,
    trip_id: SK,
    kind: 'emergency',
    title: 'Urgences & fractures',
    body: 'CHU Anglet-Bayonne : +33 5 59 44 35 35. Clinique Tivoli Bordeaux pour urgences légères. Garder ice pack dans la glacière — chutes sur béton, ça arrive.',
    icon_name: 'Flame',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },
]
