// lib/demo/fixtures-tokyo.ts — City break solo Tokyo, Lina seule, voyage TERMINÉ.
//
// 8 jours · 12–19 janvier 2026 · ~30 activités · 18 spots · 25 dépenses · 12 checklist · 6 guide cards

import type {
  LocalTrip,
  LocalTripMember,
  LocalDay,
  LocalActivity,
  LocalActivityCompletion,
  LocalSpot,
  LocalExpense,
  LocalExpenseSplit,
  LocalChecklistItem,
  LocalChecklistCompletion,
  LocalGuideCard,
} from '@/lib/db/schema'

import { DEMO_USER_ID } from './fixtures'

const NOW = new Date('2026-05-21T10:00:00Z').toISOString()
const TOKYO = 'demo-trip-tokyo'

// ─── Trip ────────────────────────────────────────────────────────────────────
export const tokyoTrip: LocalTrip = {
  id: TOKYO,
  owner_id: DEMO_USER_ID,
  name: 'Tokyo solo',
  destination: 'Tokyo, Japon',
  start_date: '2026-01-12',
  end_date: '2026-01-19',
  trip_type: 'city_break',
  currency: 'JPY',
  total_budget: 280000,
  cover_color: '#B14E32',
  join_code: 'MKT-DEMO5',
  hero_image_url: '/heroes/city_break/1.jpg',
  hero_image_uploaded: false,
  created_at: NOW,
  updated_at: NOW,
}

// ─── Members ─────────────────────────────────────────────────────────────────
export const tokyoMembers: LocalTripMember[] = [
  { trip_id: TOKYO, user_id: DEMO_USER_ID, role: 'owner', joined_at: NOW },
]

// ─── Days ────────────────────────────────────────────────────────────────────
export const tokyoDays: LocalDay[] = [
  {
    id: `${TOKYO}-d1`,
    trip_id: TOKYO,
    day_number: 1,
    date: '2026-01-12',
    label: 'Jour 1',
    theme: 'Arrivée Narita → Shinjuku',
    zone: 'Shinjuku',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d2`,
    trip_id: TOKYO,
    day_number: 2,
    date: '2026-01-13',
    label: 'Jour 2',
    theme: 'Shibuya — Hachiko & Don Quijote',
    zone: 'Shibuya',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d3`,
    trip_id: TOKYO,
    day_number: 3,
    date: '2026-01-14',
    label: 'Jour 3',
    theme: 'Harajuku · Meiji Jingu · Yoyogi',
    zone: 'Harajuku',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d4`,
    trip_id: TOKYO,
    day_number: 4,
    date: '2026-01-15',
    label: 'Jour 4',
    theme: 'Asakusa · Senso-ji · Skytree',
    zone: 'Asakusa',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d5`,
    trip_id: TOKYO,
    day_number: 5,
    date: '2026-01-16',
    label: 'Jour 5',
    theme: 'Kamakura — Daibutsu & plage',
    zone: 'Kamakura',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d6`,
    trip_id: TOKYO,
    day_number: 6,
    date: '2026-01-17',
    label: 'Jour 6',
    theme: 'Tsukiji · Ginza · Akihabara',
    zone: 'Tsukiji',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d7`,
    trip_id: TOKYO,
    day_number: 7,
    date: '2026-01-18',
    label: 'Jour 7',
    theme: 'Daikanyama · Nakameguro · Rikugien',
    zone: 'Meguro',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d8`,
    trip_id: TOKYO,
    day_number: 8,
    date: '2026-01-19',
    label: 'Jour 8',
    theme: 'Yoyogi-Hachiman brunch → Narita',
    zone: 'Shibuya',
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Activities ──────────────────────────────────────────────────────────────
export const tokyoActivities: LocalActivity[] = [
  // J1 — Arrivée Narita → Shinjuku
  {
    id: `${TOKYO}-d1-a0`,
    day_id: `${TOKYO}-d1`,
    time: '09:30',
    title: 'Atterrissage Narita T2',
    subtitle: 'Air France AF275 · perdue 20 min à trouver le bon guichet IC',
    category: 'activity',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d1-a1`,
    day_id: `${TOKYO}-d1`,
    time: '11:30',
    title: 'Narita Express → Shinjuku',
    subtitle: "3 200¥ · 1h30 · s'endormir direct dans le siège chauffant",
    category: 'activity',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d1-a2`,
    day_id: `${TOKYO}-d1`,
    time: '13:30',
    title: 'Check-in Hotel Century Southern Tower',
    subtitle: 'Shinjuku · vue sur le parc depuis le 20e — vaut le prix',
    category: 'accommodation',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d1-a3`,
    day_id: `${TOKYO}-d1`,
    time: '16:00',
    title: 'Shinjuku Gyoen — parc impérial',
    subtitle: 'Entrée 500¥ · vide en hiver, lumière dorée de 16h magnifique',
    category: 'nature',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d1-a4`,
    day_id: `${TOKYO}-d1`,
    time: '19:30',
    title: 'Ichiran Ramen — Shinjuku',
    subtitle: "Queue 45 min pour 920¥ · cabine solo · valait chaque seconde d'attente",
    category: 'food',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // J2 — Shibuya
  {
    id: `${TOKYO}-d2-a0`,
    day_id: `${TOKYO}-d2`,
    time: '08:30',
    title: 'Onibus Coffee — Nakameguro',
    subtitle: 'Café filtre 650¥ · le meilleur flat white de tout le séjour',
    category: 'food',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d2-a1`,
    day_id: `${TOKYO}-d2`,
    time: '10:00',
    title: 'Shibuya Crossing — scramble',
    subtitle: 'Se poster sur la terrasse Starbucks pour la vue · gratis',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d2-a2`,
    day_id: `${TOKYO}-d2`,
    time: '11:00',
    title: 'Hachiko — statue & quartier',
    subtitle: 'Le chien fidèle · photo en 3 essais pour éviter les selfies',
    category: 'culture',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d2-a3`,
    day_id: `${TOKYO}-d2`,
    time: '14:00',
    title: 'Don Quijote Shibuya — 6 étages',
    subtitle: 'Labyrinthe sensoriel · sortie 45 min plus tard avec trop de choses',
    category: 'activity',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d2-a4`,
    day_id: `${TOKYO}-d2`,
    time: '19:00',
    title: 'Afuri Ramen — Shibuya',
    subtitle: 'Shio yuzu ramen 1 100¥ · léger et parfait après le jet lag',
    category: 'food',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // J3 — Harajuku + Meiji Jingu + Yoyogi
  {
    id: `${TOKYO}-d3-a0`,
    day_id: `${TOKYO}-d3`,
    time: '09:00',
    title: 'Meiji Jingu — cérémonie du matin',
    subtitle: 'Forêt de 70 000 arbres · silence improbable au cœur de Tokyo',
    category: 'culture',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d3-a1`,
    day_id: `${TOKYO}-d3`,
    time: '11:00',
    title: 'Takeshita Street — Harajuku',
    subtitle: 'Crepes à 600¥ · défilé de tenues impossibles',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d3-a2`,
    day_id: `${TOKYO}-d3`,
    time: '13:30',
    title: 'Yoyogi-koen — pique-nique',
    subtitle: 'Onigiri 250¥/pièce au FamilyMart · groupes de taiko le dimanche',
    category: 'nature',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d3-a3`,
    day_id: `${TOKYO}-d3`,
    time: '16:30',
    title: 'teamLab Planets — Toyosu',
    subtitle: 'Réservé en avance 3 200¥ · vaut chaque yen · pieds nus dans l\'eau',
    category: 'culture',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },

  // J4 — Asakusa + Skytree + Senso-ji
  {
    id: `${TOKYO}-d4-a0`,
    day_id: `${TOKYO}-d4`,
    time: '07:30',
    title: 'Senso-ji au lever du soleil',
    subtitle: 'Arriver avant 8h pour voir le temple sans touristes',
    category: 'culture',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d4-a1`,
    day_id: `${TOKYO}-d4`,
    time: '09:00',
    title: 'Nakamise-dori — boutiques d\'omiyage',
    subtitle: 'Ningyo-yaki chaud 3 pièces pour 400¥ · brûlant mais parfait',
    category: 'food',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d4-a2`,
    day_id: `${TOKYO}-d4`,
    time: '11:00',
    title: 'Tokyo Skytree — 350m',
    subtitle: 'Entrée 2 100¥ · vue Fuji au nord-ouest si temps clair',
    category: 'activity',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d4-a3`,
    day_id: `${TOKYO}-d4`,
    time: '14:30',
    title: 'Sumida-koen — balade rivière',
    subtitle: 'Vent glacial mais vue Skytree depuis les ponts',
    category: 'nature',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d4-a4`,
    day_id: `${TOKYO}-d4`,
    time: '19:00',
    title: 'Izakaya Asahi — Asakusa',
    subtitle: 'Yakitori + Asahi draft 2 200¥ · bruyant, chaleureux, parfait',
    category: 'food',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },

  // J5 — Kamakura
  {
    id: `${TOKYO}-d5-a0`,
    day_id: `${TOKYO}-d5`,
    time: '07:30',
    title: 'JR Yokosuka Line → Kamakura',
    subtitle: '55 min depuis Shinjuku · 920¥ avec Suica',
    category: 'activity',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d5-a1`,
    day_id: `${TOKYO}-d5`,
    time: '09:30',
    title: 'Kotoku-in — Grand Bouddha de Kamakura',
    subtitle: 'Daibutsu 13,5m · entrée 300¥ · rentrer à l\'intérieur 20¥',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d5-a2`,
    day_id: `${TOKYO}-d5`,
    time: '12:00',
    title: 'Yuigahama Beach — déjeuner vue mer',
    subtitle: 'Shirasu don (poisson blanc) 950¥ · plage déserte en janvier',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d5-a3`,
    day_id: `${TOKYO}-d5`,
    time: '14:30',
    title: 'Tsurugaoka Hachimangu',
    subtitle: 'Grand sanctuaire shinto · enjambement de lotus gelés',
    category: 'culture',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },

  // J6 — Tsukiji + Ginza + Akihabara
  {
    id: `${TOKYO}-d6-a0`,
    day_id: `${TOKYO}-d6`,
    time: '06:30',
    title: 'Marché extérieur de Tsukiji',
    subtitle: 'Arriver à l\'ouverture pour les maguro don à 1 200¥',
    category: 'food',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d6-a1`,
    day_id: `${TOKYO}-d6`,
    time: '10:00',
    title: 'Ginza Six — architecture Kengo Kuma',
    subtitle: 'Flâner sans acheter, roof garden gratuit au 13e',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d6-a2`,
    day_id: `${TOKYO}-d6`,
    time: '13:00',
    title: 'Sushi Kanesaka — Ginza',
    subtitle: 'Omakase 15 pièces 8 800¥ · le meilleur repas du voyage',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d6-a3`,
    day_id: `${TOKYO}-d6`,
    time: '16:00',
    title: 'Akihabara — Electric Town',
    subtitle: 'Yodobashi Camera 7 étages + maid café par curiosité 700¥',
    category: 'activity',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },

  // J7 — Daikanyama + Nakameguro + Rikugien
  {
    id: `${TOKYO}-d7-a0`,
    day_id: `${TOKYO}-d7`,
    time: '09:30',
    title: 'Daikanyama T-Site — librairie',
    subtitle: 'Tsutaya Books parmi les pins · café Anjin 700¥',
    category: 'culture',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d7-a1`,
    day_id: `${TOKYO}-d7`,
    time: '11:30',
    title: 'Nakameguro — canal en hiver',
    subtitle: 'Boutiques vintage + mochi chaud 350¥ · calme sans les cerisiers',
    category: 'nature',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d7-a2`,
    day_id: `${TOKYO}-d7`,
    time: '14:00',
    title: 'Bills — brunch tardif',
    subtitle: 'Ricotta pancakes 1 800¥ · terrasse, soleil froid, parfait',
    category: 'food',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d7-a3`,
    day_id: `${TOKYO}-d7`,
    time: '16:00',
    title: 'Rikugien — jardin japonais illuminé',
    subtitle: 'Illuminations hiver 300¥ · pleuvoir doucement, parapluie du konbini',
    category: 'nature',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },

  // J8 — Yoyogi-Hachiman + Narita
  {
    id: `${TOKYO}-d8-a0`,
    day_id: `${TOKYO}-d8`,
    time: '09:00',
    title: 'Fuglen Tokyo — café norvégien',
    subtitle: 'Batch brew 600¥ · croissant beurre · dernier matin paisible',
    category: 'food',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d8-a1`,
    day_id: `${TOKYO}-d8`,
    time: '10:30',
    title: 'Yoyogi-Hachiman jinja',
    subtitle: 'Micro-sanctuaire de quartier · offrande 100¥ · zen',
    category: 'culture',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d8-a2`,
    day_id: `${TOKYO}-d8`,
    time: '13:00',
    title: 'Check-out hotel + bagages consigne',
    subtitle: 'Coin lockers Shinjuku Station 700¥ · liberté pour les 3h finales',
    category: 'accommodation',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-d8-a3`,
    day_id: `${TOKYO}-d8`,
    time: '16:00',
    title: 'Narita Express retour → T2',
    subtitle: 'Vol AF276 · 8 nuits de Tokyo dans les yeux',
    category: 'activity',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
]

// ─── Completions — TOUTES cochées par Lina ────────────────────────────────────
export const tokyoCompletions: LocalActivityCompletion[] = tokyoActivities.map((a) => {
  const dayKey = a.day_id.split('-d')[1]
  const dateMap: Record<string, string> = {
    '1': '2026-01-12T22:00:00Z',
    '2': '2026-01-13T22:00:00Z',
    '3': '2026-01-14T22:00:00Z',
    '4': '2026-01-15T22:00:00Z',
    '5': '2026-01-16T22:00:00Z',
    '6': '2026-01-17T22:00:00Z',
    '7': '2026-01-18T22:00:00Z',
    '8': '2026-01-19T20:00:00Z',
  }
  return {
    activity_id: a.id,
    user_id: DEMO_USER_ID,
    completed_at: dateMap[dayKey] ?? NOW,
  }
})

// ─── Spots ───────────────────────────────────────────────────────────────────
export const tokyoSpots: LocalSpot[] = [
  { id: `${TOKYO}-s1`, trip_id: TOKYO, name: 'Hotel Century Southern Tower', description: 'Vue sur Shinjuku Gyoen depuis le 20e', category: 'accommodation', zone: 'Shinjuku', lat: 35.6871, lng: 139.7007, price: '18 000¥/nuit', tags: ['vue', 'central'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s2`, trip_id: TOKYO, name: 'Ichiran Ramen Shinjuku', description: 'Ramen tonkotsu en cabine solo, queue garantie', category: 'food', zone: 'Shinjuku', lat: 35.6940, lng: 139.7004, price: '920¥', tags: ['ramen', 'solo'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s3`, trip_id: TOKYO, name: 'Onibus Coffee', description: 'Meilleur café spécialité de Tokyo', category: 'food', zone: 'Nakameguro', lat: 35.6436, lng: 139.7002, price: '650¥', tags: ['specialty coffee'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s4`, trip_id: TOKYO, name: 'Shibuya Crossing', description: 'Le carrefour le plus filmé du monde', category: 'culture', zone: 'Shibuya', lat: 35.6595, lng: 139.7004, price: null, tags: ['icone', 'gratuit'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s5`, trip_id: TOKYO, name: 'Afuri Ramen Shibuya', description: 'Shio yuzu ramen léger, bouillon citronné', category: 'food', zone: 'Shibuya', lat: 35.6611, lng: 139.6995, price: '1 100¥', tags: ['ramen', 'yuzu'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s6`, trip_id: TOKYO, name: 'Meiji Jingu', description: 'Forêt de 70 000 arbres en plein Harajuku', category: 'culture', zone: 'Harajuku', lat: 35.6763, lng: 139.6993, price: 'libre', tags: ['shinto', 'forêt'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s7`, trip_id: TOKYO, name: 'teamLab Planets Toyosu', description: 'Art numérique immersif, pieds nus requis', category: 'culture', zone: 'Toyosu', lat: 35.6492, lng: 139.7953, price: '3 200¥', tags: ['art', 'expérience'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s8`, trip_id: TOKYO, name: 'Senso-ji', description: 'Temple bouddhiste d\'Asakusa, 1 300 ans', category: 'culture', zone: 'Asakusa', lat: 35.7148, lng: 139.7967, price: 'libre', tags: ['temple', 'touristique'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s9`, trip_id: TOKYO, name: 'Tokyo Skytree', description: '634m, 2e tour la plus haute du monde', category: 'activity', zone: 'Asakusa', lat: 35.7101, lng: 139.8107, price: '2 100¥', tags: ['vue', 'tour'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s10`, trip_id: TOKYO, name: 'Kotoku-in Daibutsu Kamakura', description: 'Grand Bouddha en bronze de 13,5m', category: 'culture', zone: 'Kamakura', lat: 35.3167, lng: 139.5352, price: '300¥', tags: ['bouddhisme', 'heritage'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s11`, trip_id: TOKYO, name: 'Yuigahama Beach', description: 'Plage de Kamakura, calme en janvier', category: 'nature', zone: 'Kamakura', lat: 35.3100, lng: 139.5490, price: null, tags: ['plage', 'hiver'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s12`, trip_id: TOKYO, name: 'Marché extérieur Tsukiji', description: 'Thon, fruits de mer, poisson grillé à l\'ouverture', category: 'food', zone: 'Tsukiji', lat: 35.6654, lng: 139.7707, price: 'varie', tags: ['marché', 'matin'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s13`, trip_id: TOKYO, name: 'Sushi Kanesaka', description: 'Omakase haut-de-gamme Ginza', category: 'food', zone: 'Ginza', lat: 35.6705, lng: 139.7650, price: '8 800¥', tags: ['sushi', 'gastronomie'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s14`, trip_id: TOKYO, name: 'Daikanyama T-Site', description: 'Librairie Tsutaya iconique, architecture parmi les pins', category: 'culture', zone: 'Daikanyama', lat: 35.6483, lng: 139.7025, price: 'libre', tags: ['librairie', 'design'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s15`, trip_id: TOKYO, name: 'Nakameguro canal', description: 'Balade le long du canal, boutiques vintage', category: 'nature', zone: 'Nakameguro', lat: 35.6430, lng: 139.6990, price: null, tags: ['canal', 'promenade'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s16`, trip_id: TOKYO, name: 'Bills Nakameguro', description: 'Brunch australien, ricotta pancakes légendaires', category: 'food', zone: 'Nakameguro', lat: 35.6440, lng: 139.6981, price: '1 800¥', tags: ['brunch', 'pancakes'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s17`, trip_id: TOKYO, name: 'Rikugien Garden', description: 'Jardin d\'Edo illuminé en hiver, prunus centenaires', category: 'nature', zone: 'Komagome', lat: 35.7352, lng: 139.7465, price: '300¥', tags: ['jardin', 'illumination'], created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-s18`, trip_id: TOKYO, name: 'Fuglen Tokyo', description: 'Café norvégien à Yoyogi-Hachiman, torréfaction soignée', category: 'food', zone: 'Yoyogi', lat: 35.6736, lng: 139.6917, price: '600¥', tags: ['café', 'norvégien'], created_at: NOW, updated_at: NOW },
]

// ─── Expenses — 25 dépenses en ¥ ─────────────────────────────────────────────
export const tokyoExpenses: LocalExpense[] = [
  { id: `${TOKYO}-e1`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 126000, currency: 'JPY', category: 'hotel', note: 'Hotel Century Southern Tower · 7 nuits', spent_at: '2026-01-12T14:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e2`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 85000, currency: 'JPY', category: 'transport', note: 'Vol AF A/R Paris-Tokyo', spent_at: '2025-11-20T10:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e3`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 6400, currency: 'JPY', category: 'transport', note: 'Narita Express A/R', spent_at: '2026-01-12T10:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e4`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 5000, currency: 'JPY', category: 'transport', note: 'Suica IC rechargements × 3', spent_at: '2026-01-12T11:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e5`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 920, currency: 'JPY', category: 'food', note: 'Ichiran Ramen Shinjuku', spent_at: '2026-01-12T20:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e6`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 650, currency: 'JPY', category: 'drink', note: 'Onibus Coffee — café filtre', spent_at: '2026-01-13T08:30:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e7`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 1100, currency: 'JPY', category: 'food', note: 'Afuri Ramen shio yuzu', spent_at: '2026-01-13T19:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e8`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 3800, currency: 'JPY', category: 'shopping', note: 'Don Quijote — snacks + omiyage', spent_at: '2026-01-13T15:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e9`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 3200, currency: 'JPY', category: 'activity', note: 'teamLab Planets Toyosu', spent_at: '2026-01-14T16:30:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e10`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 500, currency: 'JPY', category: 'activity', note: 'Shinjuku Gyoen entrée', spent_at: '2026-01-12T16:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e11`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 2100, currency: 'JPY', category: 'activity', note: 'Tokyo Skytree Tembo Deck', spent_at: '2026-01-15T11:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e12`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 2200, currency: 'JPY', category: 'food', note: 'Izakaya Asahi Asakusa — yakitori + bière', spent_at: '2026-01-15T19:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e13`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 920, currency: 'JPY', category: 'transport', note: 'JR Kamakura A/R depuis Shinjuku', spent_at: '2026-01-16T07:30:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e14`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 300, currency: 'JPY', category: 'activity', note: 'Kotoku-in Daibutsu entrée', spent_at: '2026-01-16T09:30:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e15`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 950, currency: 'JPY', category: 'food', note: 'Shirasu don à Yuigahama', spent_at: '2026-01-16T12:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e16`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 1200, currency: 'JPY', category: 'food', note: 'Maguro don Tsukiji matin', spent_at: '2026-01-17T06:30:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e17`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 8800, currency: 'JPY', category: 'food', note: 'Omakase Sushi Kanesaka Ginza', spent_at: '2026-01-17T13:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e18`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 700, currency: 'JPY', category: 'activity', note: 'Maid café curiosité Akihabara', spent_at: '2026-01-17T17:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e19`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 700, currency: 'JPY', category: 'drink', note: 'Café Anjin Daikanyama T-Site', spent_at: '2026-01-18T09:30:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e20`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 1800, currency: 'JPY', category: 'food', note: 'Bills brunch ricotta pancakes', spent_at: '2026-01-18T14:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e21`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 300, currency: 'JPY', category: 'activity', note: 'Rikugien illuminations hivernales', spent_at: '2026-01-18T16:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e22`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 12000, currency: 'JPY', category: 'shopping', note: 'Omiyage Shinjuku (thé, wagashi, sake miniature)', spent_at: '2026-01-18T17:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e23`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 600, currency: 'JPY', category: 'drink', note: 'Fuglen Tokyo dernier café', spent_at: '2026-01-19T09:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e24`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 700, currency: 'JPY', category: 'transport', note: 'Coin lockers Shinjuku Station', spent_at: '2026-01-19T13:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-e25`, trip_id: TOKYO, payer_id: DEMO_USER_ID, amount: 3200, currency: 'JPY', category: 'transport', note: 'Narita Express retour J8', spent_at: '2026-01-19T16:00:00Z', split_mode: 'equal', created_at: NOW, updated_at: NOW },
]

// ─── Splits — 1 entrée par expense, share 1.0 ─────────────────────────────────
export const tokyoSplits: LocalExpenseSplit[] = tokyoExpenses.map((e) => ({
  expense_id: e.id,
  user_id: DEMO_USER_ID,
  share: 1.0,
}))

// ─── Checklist — 12 items, TOUS cochés ───────────────────────────────────────
export const tokyoChecklist: LocalChecklistItem[] = [
  { id: `${TOKYO}-c1`, trip_id: TOKYO, label: 'Passeport valide + photocopie numérique', category: 'docs', position: 0, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c2`, trip_id: TOKYO, label: 'Visa Japon (exemption 90j passeport FR)', category: 'docs', position: 1, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c3`, trip_id: TOKYO, label: 'JR Pass 7 jours commandé en ligne', category: 'docs', position: 2, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c4`, trip_id: TOKYO, label: 'Suica IC card Narita Express', category: 'docs', position: 3, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c5`, trip_id: TOKYO, label: 'eSIM Japon (Ubigi ou Airalo)', category: 'gear', position: 4, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c6`, trip_id: TOKYO, label: 'Adaptateur Type A (Japon = US plug)', category: 'gear', position: 5, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c7`, trip_id: TOKYO, label: 'Doudoune légère (janvier ~6°C à Tokyo)', category: 'clothing', position: 6, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c8`, trip_id: TOKYO, label: 'Chaussures de marche confortables', category: 'clothing', position: 7, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c9`, trip_id: TOKYO, label: 'Réserver teamLab Planets à l\'avance', category: 'other', position: 8, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c10`, trip_id: TOKYO, label: 'Cash ¥ — beaucoup de restaurants no card', category: 'other', position: 9, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c11`, trip_id: TOKYO, label: 'App Google Maps offline + Maps.me', category: 'other', position: 10, created_at: NOW, updated_at: NOW },
  { id: `${TOKYO}-c12`, trip_id: TOKYO, label: 'Assurance voyage + couverture médicale', category: 'docs', position: 11, created_at: NOW, updated_at: NOW },
]

// Voyage terminé : TOUS cochés par Lina
export const tokyoChecklistDone: LocalChecklistCompletion[] = tokyoChecklist.map((it) => ({
  item_id: it.id,
  user_id: DEMO_USER_ID,
  completed_at: '2026-01-10T18:00:00Z',
}))

// ─── Guide Cards ──────────────────────────────────────────────────────────────
export const tokyoGuide: LocalGuideCard[] = [
  {
    id: `${TOKYO}-g1`,
    trip_id: TOKYO,
    kind: 'warning',
    title: 'Métro aux heures de pointe',
    body: 'Trains bondés 8h-9h30 et 18h30-20h. Éviter avec des bagages. Pousser dans la rame est la norme — ne pas résister.',
    icon_name: 'AlertTriangle',
    position: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-g2`,
    trip_id: TOKYO,
    kind: 'info',
    title: 'Paiement IC vs cash',
    body: 'Suica Felica acceptée dans konbini, métro, 7-Eleven. Restaurants gastronomiques = cash seulement. Toujours garder 5 000¥ en poche.',
    icon_name: 'CreditCard',
    position: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-g3`,
    trip_id: TOKYO,
    kind: 'weather',
    title: 'Janvier à Tokyo — sec et froid',
    body: 'Températures 4-10°C, humidité basse, ciel souvent bleu. Fuji visible par temps clair depuis Skytree. Doudoune + couches obligatoires le soir.',
    icon_name: 'Cloud',
    position: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-g4`,
    trip_id: TOKYO,
    kind: 'emergency',
    title: 'Urgences Japon',
    body: 'Police : 110 · Pompiers/SAMU : 119 · Hôpital anglophone Tokyo : St. Luke\'s International (Chuo-ku). Ambassade de France : 03-5798-6000.',
    icon_name: 'Flame',
    position: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-g5`,
    trip_id: TOKYO,
    kind: 'food',
    title: 'Conseils table au Japon',
    body: 'Pas de pourboire — insultant. Itadakimasu avant, gochisosama après. Slurper ses ramen = compliment. Baguettes : jamais plantées verticalement dans le riz.',
    icon_name: 'UtensilsCrossed',
    position: 4,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: `${TOKYO}-g6`,
    trip_id: TOKYO,
    kind: 'danger',
    title: 'Étiquette téléphone + bruit',
    body: 'Téléphone en mode silencieux dans le métro. Appels interdits dans les wagons. Parler bas — les locaux parlent à peine. Couvrir sa bouche si on tousse.',
    icon_name: 'Volume2',
    position: 5,
    created_at: NOW,
    updated_at: NOW,
  },
]
